// Файл, который поможет Вам создать товар.
package woocommerce

import (
	"encoding/json"
	"errors"
)

// Структура добавления товара
type AutoGenerated struct {
	Name             string `json:"name"`
	Type             string `json:"type"`
	RegularPrice     string `json:"regular_price"`
	Description      string `json:"description"`
	ShortDescription string `json:"short_description"`
	Categories       []struct {
		ID int `json:"id"`
	} `json:"categories"`
	Images []struct {
		Src string `json:"src"`
	} `json:"images"`
}

// Метод [products] поможет Вам добавить товар
//
// # Использую для добавления товара
//
// [products]: http://woocommerce.github.io/woocommerce-rest-api-docs/?shell#create-a-product
func (user *User) AddProduct_WC(valetCat MeCat) (int, error) {

	// Сделать json добавления категории
	bytesData, errMarshal := json.Marshal(valetCat)
	if errMarshal != nil {
		return 0, errMarshal
	}

	// Выполнить запрос
	bodyBytes, errData := user.quering("POST", "/products/categories", bytesData)
	if errData != nil {
		return 0, errData
	}

	// Получить ответ
	var AddCatRes AddCatResponse
	errUnmarshal := json.Unmarshal(bodyBytes, &AddCatRes)
	if errUnmarshal != nil { // Если ошибка распарсивания в структуру данных
		return 0, errors.New("AddCat_WC: Не удалось распарсить ответ сервера: " + string(bodyBytes))
	}
	if AddCatRes.Code == "term_exists" { // Обработка случая, когда существует такая категория
		return AddCatRes.Data.ResourceID, nil
	}

	// Если всё верно сработало и произошло добавление
	return AddCatRes.ID, nil
}
